//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public string number { get; set; }
        public int RouteId { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
