//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public Link()
        {
            this.Stationss = new HashSet<Station>();
        }
    
        public int Id { get; set; }
        public string time { get; set; }
        public int RouteId { get; set; }
        public int StationId { get; set; }
        public int StationId1 { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual ICollection<Station> Stationss { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
