//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Linkss = new HashSet<Link>();
            this.Link = new HashSet<Link>();
            this.Link1 = new HashSet<Link>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Link> Linkss { get; set; }
        public virtual ICollection<Link> Link { get; set; }
        public virtual ICollection<Link> Link1 { get; set; }
    }
}
